apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mesh-app-mssql-secret
  namespace: mesh-apps
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: pineapple.secretsmgr.cyberark.cloud
    kind: SecretStore
  data:
  - secretKey: address
    remoteRef:
      key: data/vault/PIN-MSSQL-ADM/Database-PL-MYSQL-A-readonly/address
  - secretKey: username
    remoteRef:
      key: data/vault/PIN-MSSQL-ADM/Database-PL-MYSQL-A-readonly/username
  - secretKey: password
    remoteRef:
      key: data/vault/PIN-MSSQL-ADM/Database-PL-MYSQL-A-readonly/password