apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pineapple.secretsmgr.cyberark.cloud
  namespace: mesh-apps
spec:
  provider:
    conjur:
      url: https://pineapple.secretsmgr.cyberark.cloud/api
      auth:
        jwt:
          account: conjur
          serviceID: eso-jwt-mesh-apps
          serviceAccountRef:
            name: productcatalogservice
            audiences:
              - https://pineapple.secretsmgr.cyberark.cloud