---

- name: Remove pre-requisites (Ubuntu)
  become: true
  apt:
    name:
      - kubectl
    state: absent
  when: ansible_os_family == 'Debian'
  tags:
    - clean

- name: Remove kind binary (Ubuntu)
  become: true
  file:
    path: /usr/local/bin/kind
    state: absent
  when: ansible_os_family == 'Debian'
  tags:
    - clean

- name: Remove pre-requisites (MacOS)
  homebrew:
    package: "{{ items }}"
    state: absent
  loop:
    - kind
    - kubectl
    - docker
  when: ansible_os_family == 'Darwin'
  tags:
    - clean
