- !policy
  id: eso-jwt-mesh-apps
  body:
    - !webservice

    - !variable token-app-property
    - !variable identity-path
    - !variable issuer
    - !variable public-keys

    - !group apps

    - !permit
      role: !group apps
      privileges: [ read, authenticate ]
      resource: !webservice