- !delete
  record: !webservice eso-jwt-mesh-apps
- !delete
  record: !group eso-jwt-mesh-apps/apps
- !delete
  record: !variable eso-jwt-mesh-apps/identity-path
- !delete
  record: !variable eso-jwt-mesh-apps/issuer
- !delete
  record: !variable eso-jwt-mesh-apps/public-keys
- !delete
  record: !variable eso-jwt-mesh-apps/token-app-property
- !delete
  record: !policy eso-jwt-mesh-apps