- name: Generate and deploy expiry-eddie certificate
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cert_path: "files/artifacts/samples/expiry-eddie-cert.crt"
    key_path: "files/artifacts/samples/expiry-eddie-key.key"
  tasks:
    - name: Create Long Duration Certificate Request
      ansible.builtin.copy:
        src: "files/templates/certs/02-expiry-eddie-cert.yaml"
        dest: "files/artifacts/samples/02-expiry-eddie-cert.yaml"
        mode: '0644'
    
    - name: Apply Long Duration Certificate Request
      kubernetes.core.k8s:
        state: present
        namespace: sandbox
        src: "files/artifacts/samples/02-expiry-eddie-cert.yaml"

    - name: Generate RSA private key
      community.crypto.openssl_privatekey:
        path: files/artifacts/samples/expiry-eddie-key.key
        size: 2048
        mode: '0644'

    - name: Generate a self-signed certificate
      community.crypto.x509_certificate:
        path: files/artifacts/samples/expiry-eddie-cert.crt
        privatekey_path: files/artifacts/samples/expiry-eddie-key.key
        provider: selfsigned
        selfsigned_not_before: "+0s"
        selfsigned_not_after: "+365d"
        selfsigned_digest: "sha256"
        selfsigned_create_subject_key_identifier: create_if_not_provided
        selfsigned_version: 3
        mode: '0644'

    - name: Read key file content
      ansible.builtin.slurp:
        src: "{{ key_path }}"
      register: key_content

    - name: Read certificate file content
      ansible.builtin.slurp:
        src: "{{ cert_path }}"
      register: cert_content

    - name: Create expiry-eddie TLS secret in Kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: expiry-eddie.svc.cluster.local
            namespace: sandbox
          type: kubernetes.io/tls
          data:
            tls.crt: "{{ cert_content['content'] }}"
            tls.key: "{{ key_content['content'] }}"

    - name: Deploy expiry-eddie Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: expiry-eddie-nginx
            namespace: sandbox
          spec:
            type: NodePort
            ports:
              - port: 80
            selector:
              app: expiry-eddie-nginx

    - name: Deploy expiry-eddie Nginx
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            labels:
              app: expiry-eddie-nginx
            name: expiry-eddie-nginx
            namespace: sandbox
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: expiry-eddie-nginx
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  app: expiry-eddie-nginx
              spec:
                containers:
                  - image: nginx:latest
                    name: expiry-eddie-nginx
                    volumeMounts:
                      - mountPath: "/etc/expiry-eddie-nginx/ssl"
                        name: expiry-eddie-nginx-ssl
                        readOnly: true
                    ports:
                      - containerPort: 80
                volumes:
                  - name: expiry-eddie-nginx-ssl
                    secret:
                      secretName: expiry-eddie.svc.cluster.local
                restartPolicy: Always
