---
- name: Create Venafi Service Accounts
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Create Discovery Service Account
      ansible.builtin.command:
        cmd: >
          venctl iam service-accounts agent create
          --name "demo-agent-{{ resource_suffix }}"
          --output-file "files/artifacts/venafi-install/venafi_agent_secret.json"
          --output "secret"
          --owning-team "{{ team_name }}"
          --validity 10
          --api-key "{{ venaficloud_api_key }}"
      register: venafi_result
      changed_when: "'Created' in venafi_result.stdout"

    - name: Read Venafi Agent Secret JSON
      ansible.builtin.slurp:
        src: "files/artifacts/venafi-install/venafi_agent_secret.json"
      register: agent_secret_json

    - name: Parse JSON and Extract Private Key
      ansible.builtin.copy:
        content: "{{ (agent_secret_json['content'] | b64decode | from_json).private_key }}"
        dest: "files/artifacts/venafi-install/venafi_agent_secret.yaml"
        mode: '0644'

    - name: Parse JSON and Extract Client ID
      ansible.builtin.copy:
        content: "{{ (agent_secret_json['content'] | b64decode | from_json).client_id }}"
        dest: "files/artifacts/venafi-install/venafi_agent_client_id.txt"
        mode: '0644'

    - name: Create Registry Service Account
      ansible.builtin.command:
        cmd: >
          venctl iam service-account registry create
          --name "demo-secret-{{ resource_suffix }}"
          --output-file "files/artifacts/venafi-install/venafi_registry_secret.json"
          --output "secret"
          --owning-team "{{ team_name }}"
          --validity 10
          --scopes enterprise-cert-manager,enterprise-approver-policy,enterprise-venafi-issuer
          --api-key "{{ venaficloud_api_key }}"
      register: venafi_result
      changed_when: "'Created' in venafi_result.stdout"
    
    - name: Read Venafi Registry Secret JSON
      ansible.builtin.slurp:
        src: "files/artifacts/venafi-install/venafi_registry_secret.json"
      register: registry_secret_json

    - name: Parse JSON and Extract Image Pull Secret
      ansible.builtin.copy:
        content: "{{ (registry_secret_json['content'] | b64decode | from_json).image_pull_secret }}"
        dest: "files/artifacts/venafi-install/venafi_registry_secret.yaml"
        mode: '0644'

    - name: Create Firefly Service Account
      ansible.builtin.command:
        cmd: >
          venctl iam service-accounts firefly create
          --name "demo-firefly-{{ resource_suffix }}"
          --output-file "files/artifacts/venafi-install/venafi_firefly_secret.json"
          --output "secret"
          --owning-team "{{ team_name }}"
          --validity 10
          --api-key "{{ venaficloud_api_key }}"
      register: venafi_result
      changed_when: "'Created' in venafi_result.stdout"

    - name: Read Venafi Firefly Secret JSON
      ansible.builtin.slurp:
        src: "files/artifacts/venafi-install/venafi_firefly_secret.json"
      register: firefly_secret_json

    - name: Parse JSON and Extract Private Key
      ansible.builtin.copy:
        content: "{{ (firefly_secret_json['content'] | b64decode | from_json).private_key }}"
        dest: "files/artifacts/venafi-install/venafi_firefly_secret.yaml"
        mode: '0644'

    - name: Parse JSON and Extract Client ID
      ansible.builtin.copy:
        content: "{{ (firefly_secret_json['content'] | b64decode | from_json).client_id }}"
        dest: "files/artifacts/venafi-install/venafi_firefly_client_id.txt"
        mode: '0644'