---
- name: Initialize workspace
  hosts: "{{ HOSTS | default('localhost') }}"
  vars_files:
    - "{{ playbook_dir }}/vars/vars.yml"

  tasks:
    - name: Ensure jq is installed
      community.general.homebrew:
        name: jq
        state: present

    - name: Ensure clean artifacts directory
      ansible.builtin.file:
        path: "{{ playbook_dir }}/artifacts"
        state: absent

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ playbook_dir }}/artifacts/venafi-install"
        - "{{ playbook_dir }}/artifacts/config"
        - "{{ playbook_dir }}/artifacts/samples"

    - name: Run venctl installer (sudo password required)
      ansible.builtin.command:
        cmd: "/bin/bash {{ playbook_dir }}/files/venctl_installer.sh"
      args:
        creates: /usr/local/bin/venctl

    - name: Ensure Venafi namespace is applied
      community.kubernetes.k8s:
        state: present
        src: "files/namespaces/venafi.yaml"

    - name: Ensure Sandbox namespace is applied
      community.kubernetes.k8s:
        state: present
        src: "files/namespaces/sandbox.yaml"