- name: Install External Secrets Operator
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Add External Secrets Helm repository
      kubernetes.core.helm_repository:
        name: external-secrets
        repo_url: https://charts.external-secrets.io

    - name: Update Helm repositories
      ansible.builtin.command:
        cmd: helm repo update
      changed_when: true

    - name: Create namespace for External Secrets Operator
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: external-secrets

    - name: Install External Secrets Operator via Helm
      kubernetes.core.helm:
        name: external-secrets
        chart_ref: external-secrets/external-secrets
        release_namespace: external-secrets
        create_namespace: false
        wait: true
        values:
          installCRDs: true
          webhook:
            create: true
          certController:
            create: true

    - name: Wait for External Secrets pods to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: external-secrets
        label_selectors:
          - app.kubernetes.io/name=external-secrets
      register: eso_pods
      until: eso_pods.resources | length > 0 and (eso_pods.resources | map(attribute='status.phase') | select('equalto', 'Running') | list | length == eso_pods.resources | length)
      retries: 30
      delay: 10