---
- name: Install Required Dependencies
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Ensure jq is installed (Ubuntu)
      become: true
      apt:
        name: jq
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure jq is installed (MacOS)
      community.general.homebrew:
        name: jq
        state: present
      when: ansible_os_family == 'Darwin'

    - name: Download venctl installer
      ansible.builtin.get_url:
        url: "https://dl.venafi.cloud/venctl/latest/installer.sh"
        dest: "/tmp/venctl_installer.sh"
        mode: '0755'

    - name: Run venctl installer
      ansible.builtin.command:
        cmd: "/bin/bash /tmp/venctl_installer.sh"
      args:
        creates: "{{ '/usr/bin/venctl' if ansible_os_family == 'Debian' else '/usr/local/bin/venctl' }}"
