- name: Setup PrivilegeCloud Environment
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/vars.yml
  tasks:
    - name: "Discover Platform Endpoints for {{ cyberark_subdomain }}.cyberark.cloud"
      ansible.builtin.uri:
        url: "https://platform-discovery.cyberark.cloud/api/v2/services/subdomain/{{ cyberark_subdomain }}"
        method: GET
      register: cyberark_endpoints

    - name: Login to Privilege Cloud
      ansible.builtin.uri:
        url: "{{ cyberark_endpoints.json.identity_administration.api }}/oauth2/platformtoken"
        method: POST
        follow_redirects: all
        body_format: form-urlencoded
        body:
          grant_type: client_credentials
          client_id: "{{ cyberark_service_user }}"
          client_secret: "{{ cyberark_service_secret }}"
      register: cyberark_login
      #no_log: yes

    - name: Delete cyberark-shop-demo safe
      ansible.builtin.uri:
        url: "{{ cyberark_endpoints.json.pcloud.api }}/passwordvault/api/safes/cyberark-shop-demo"
        method: DELETE
        follow_redirects: all
        headers:
          Authorization: "Bearer {{ cyberark_login.json.access_token }}"
        status_code: 204
      ignore_errors: yes