---
- name: Setup Configuration for Service Mesh
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Ensure Helm is installed
      community.general.homebrew:
        name: helm
        state: present

    - name: Apply Istio System Namespace
      kubernetes.core.k8s:
        state: present
        namespace: "istio-system"
        src: "files/namespaces/istio-system.yaml"

    - name: Apply Mesh Applications Namespace
      kubernetes.core.k8s:
        state: present
        namespace: "mesh-apps"
        src: "files/namespaces/mesh-apps.yaml"

    - name: Create Venafi Trust Anchor Secret
      kubernetes.core.k8s:
        state: present
        namespace: cyberark
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: venafi-trust-anchor
            namespace: cyberark
          type: Opaque
          data:
            root-cert.pem: "{{ lookup('file', '{{ trust_anchor_root_ca_pem }}') | b64encode }}"

    - name: Generate Istio CSR Configuration
      ansible.builtin.copy:
        src: "files/templates/helm/istio-csr-values.yaml.j2"
        dest: "files/artifacts/venafi-install/istio-csr-values.yaml"
        mode: '0644'

    - name: Apply Firefly Mesh Issuer
      kubernetes.core.k8s:
        state: present
        namespace: "istio-system"
        src: "files/templates/servicemesh/firefly-mesh-wi-issuer.yaml"

    - name: Create Istio CSR CA ConfigMap
      kubernetes.core.k8s:
        state: present
        namespace: cyberark
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: istio-csr-ca
            namespace: cyberark
          data:
            issuer-name: firefly-mesh-wi-issuer
            issuer-kind: Issuer
            issuer-group: firefly.venafi.com

    - name: Create Firefly Trust Anchor
      ansible.builtin.template:
        src: "files/templates/servicemesh/firefly-trust-anchor.yaml.j2"
        dest: "files/artifacts/venafi-install/firefly-trust-anchor.yaml"
        mode: '0644'

    - name: Apply Firefly Trust Anchor
      kubernetes.core.k8s:
        state: present
        namespace: "istio-system"
        src: "files/artifacts/venafi-install/firefly-trust-anchor.yaml"

    - name: Generate Venafi Helm manifests for Istio CSR
      ansible.builtin.command:
        cmd: |
          venctl components kubernetes manifest generate
          --namespace cyberark
          --istio-csr
          --istio-csr-version "{{ cert_manager_istio_csr_version }}"
          --istio-csr-values-files istio-csr-values.yaml
          --image-pull-secret-names venafi-image-pull-secret
      register: venafi_manifest_output
      changed_when: venafi_manifest_output.rc == 0

    - name: Save Venafi Helm manifest output to file
      ansible.builtin.copy:
        content: "{{ venafi_manifest_output.stdout }}"
        dest: "files/artifacts/venafi-install/venafi-manifests-istio.yaml"
        mode: '0644'
    
    - name: Sync Venafi Istio manifests using venctl
      ansible.builtin.command:
        cmd: |
          venctl components kubernetes manifest tool sync --file files/artifacts/venafi-install/venafi-manifests-istio.yaml
      environment:
        ISTIO_TRUST_DOMAIN: "cluster.local"
      register: venctl_sync_output
      changed_when: venctl_sync_output.rc == 0 

    - name: Install Istio Configuration
      ansible.builtin.template:
        src: "files/templates/servicemesh/istio-config.yaml.j2"
        dest: "files/artifacts/venafi-install/istio-config.yaml"
        mode: '0644'