---
- name: Deploy resources to the Sandbox namespace
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Ensure jq is installed
      community.general.homebrew:
        name: jq
        state: present

    - name: Pull nginx:latest Docker image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Load nginx:latest into Kind cluster
      ansible.builtin.command:
        cmd: "kind load docker-image nginx:latest --name demo-poc-cluster-{{ resource_suffix }}"
      register: kind_load_result
      changed_when: "'Image: ' in kind_load_result.stdout"

    - name: Ensure Sandbox namespace exists
      kubernetes.core.k8s:
        state: present
        namespace: sandbox
        src: "files/namespaces/sandbox.yaml"
    
    - name: Create Docker Hub image pull secret from local config.json
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dockerhub-creds
            namespace: sandbox
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ lookup('file', '~/.docker/config.json') | b64encode }}"


    - name: Apply Certificate Policy for Sandbox
      kubernetes.core.k8s:
        state: present
        namespace: sandbox
        src: "files/templates/common/cert-policy-and-rbac.yaml"

    - name: Deploy Sample Certificates to Sandbox
      kubernetes.core.k8s:
        state: present
        namespace: sandbox
        src: "files/samples/sample-firefly-certificates.yaml"