---
- name: Deploy resources to the Sandbox namespace
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Ensure jq is installed (Ubuntu)
      become: true
      apt:
        name: jq
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure jq is installed (MacOS)
      community.general.homebrew:
        name: jq
        state: present
      when: ansible_os_family == 'Darwin'

    - name: Pull nginx:latest Docker image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Load nginx:latest into Kind cluster
      ansible.builtin.command:
        cmd: "kind load docker-image nginx:latest --name demo-poc-cluster-{{ resource_suffix }}"
      register: kind_load_result
      changed_when: "'Image: ' in kind_load_result.stdout"

    - name: Ensure Sandbox namespace exists
      kubernetes.core.k8s:
        state: present
        namespace: sandbox
        src: "files/namespaces/sandbox.yaml"

    - name: Set Docker config path
      set_fact:
        docker_config_path: "{{ ansible_env.HOME }}/.docker/config.json"

    - name: Check if Docker config exists
      stat:
        path: "{{ docker_config_path }}"
      register: docker_config_exists

    - name: Create Docker Hub image pull secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dockerhub-creds
            namespace: sandbox
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ lookup('file', docker_config_path) | b64encode }}"
      when: docker_config_exists.stat.exists

    - name: Create empty Docker config if not exists
      block:
        - name: Warn about missing Docker config
          debug:
            msg: "Docker config not found at {{ docker_config_path }}. Creating an empty config."
        
        - name: Create Docker Hub image pull secret with empty config
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: dockerhub-creds
                namespace: sandbox
              type: kubernetes.io/dockerconfigjson
              data:
                .dockerconfigjson: "{{ '{\"auths\":{}}' | b64encode }}"
      when: not docker_config_exists.stat.exists

    - name: Apply Certificate Policy for Sandbox
      kubernetes.core.k8s:
        state: present
        namespace: sandbox
        src: "files/templates/common/cert-policy-and-rbac.yaml"

    - name: Deploy Sample Certificates to Sandbox
      kubernetes.core.k8s:
        state: present
        namespace: sandbox
        src: "files/samples/sample-firefly-certificates.yaml"
