#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Joe Garcia
  description: A role for managing Kubernetes-in-Docker clusters
  company: CyberArk
  license: MIT

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
  - kubernetes
  - docker
  - kubernetes-in-docker
  - kind
  - k8s

dependencies: []